# action.yml
name: 'Trains train model'
description: 'Clone and enqueue your task to train your model'
inputs:
  TRAINS_API_ACCESS_KEY:
    description: 'Trains api access key (can be generated in your profile page'
    required: true
  TRAINS_API_SECRET_KEY:
    description: 'Trains api secret key (can be generated in your profile page'
    required: true
  TRAINS_API_HOST:
    description: 'Trains server api host'
    required: true
  TASK_ID:
    description: 'The task id you would like to get the stats'
    required: true
branding:
  color: 'purple'
  icon: 'monitor'
runs:
  using: 'docker'
  image: 'Dockerfile'
